apiVersion: v2
name: sympozium
description: Sympozium — run a fleet of AI agents on Kubernetes
type: application
version: 0.2.1
appVersion: "0.2.1"
home: https://github.com/kasdk3/sympozium
sources:
  - https://github.com/kasdk3/sympozium
maintainers:
  - name: sympozium-ai
    url: https://github.com/sympozium-ai
  - name: kasdk3
    url: https://github.com/kasdk3
keywords:
  - kubernetes
  - ai
  - agents
  - agentic
  - llm
  - sympozium
icon: https://raw.githubusercontent.com/kasdk3/sympozium/main/icon.png